name: Release CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_on_win:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@master
     - uses: actions/setup-node@master
       with:
         node-version: 22.4
     - run: npm install
     - run: npm run build
     - uses: actions/upload-artifact@master
       with:
         name: windows-builds
         path: dist/
